name: Run tests

on:
  workflow_run:
    workflows: [build]
    types:
      - completed

jobs:
  generate_matrix:
    runs-on: ubuntu-20.04
    name: Generate test matrix
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  test:
    name: Test
    runs-on: ubuntu-20.04
    needs: generate_matrix
    steps:
    - name: Checkout
      uses: actions/checkout@v2

