name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: quay.io/389ds/ci-images:test

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check sysctl
        run: |
          set -eux
          sysctl -a | grep suid_dumpable

      - name: sysctl set 
        run: |
          set -eux
          sysctl fs.suid_dumpable=0
          sysctl -a | grep suid_dumpable

