name: Build

on: [push, pull_request]

jobs:
  on_host:
    name: Host check
    runs-on: ubuntu-20.04


    steps:
      - name: check sysctl
        run: |
          set -eux
          sysctl -a | grep suid_dumpable
          sysctl -a | grep core_pattern

      - name: sysctl set 
        run: |
          set -eux
          sysctl -w fs.suid_dumpable=0
          sysctl -a | grep suid_dumpable
         
  in_container:
    name: Container check
    runs-on: ubuntu-20.04
    container:
      image: quay.io/389ds/ci-images:test
    steps:
      - name: check sysctl
        run: |
          set -eux
          sysctl -a | grep suid_dumpable
          sysctl -a | grep core_pattern

      - name: sysctl set 
        run: |
          set -eux
          sysctl -w fs.suid_dumpable=0
          sysctl -a | grep suid_dumpable